Interactive Phel development config influenced by Emacs Cider implemented using basic stdio communication (comint style) because nRepl for Phel is not ready yet. Emulates Emacs Lisp and Clojure editing functionalities for a more frugal yet still very usable Lisp environment hosted on PHP.

Implementation is a bit rough and some things are finding their place but it works fine for everyday programming tasks.

Possibly re-worked in future with actual Cider compatibility, ref:
- https://codeberg.org/jasalt/phel-nrepl (WIP)
- https://docs.cider.mx/cider/platforms/overview.html
- https://docs.cider.mx/cider/platforms/basilisp.html

MisTTY is used as REPL session terminal which sometimes breaks a bit and needs to be restarted but mostly works. Setup is quite naive and MistTTy is "reserved" for Phel, there's probably some quirks when using it for different tasks on same Emacs instance.

* TODO
See also TODO items in code.
** TODO research usage with project.el and
** TODO research https://github.com/licht1stein/babashka.el/blob/master/babashka.el
